[package]
name = "cexio"
version = "0.4.1"
authors = ["Sergey Isaev <isvforall@gmail.com>"]
edition = "2018"

description = "Client for Cex.io crypto exchange API"
keywords = ["cexio", "cryptocurrency", "trading", "bitcoin", "crypto"]
license = "MIT"
repository = "https://github.com/isvforall/cexio"
homepage = "https://github.com/isvforall/cexio"
documentation = "https://docs.rs/cexio"
readme = "README.md"
categories = ["api-bindings"]
include = [
    "**/*.rs",
    "Cargo.toml",
]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.10.0", features = ["blocking", "json"] }
serde = { version = "1.0.104", features = ["derive"] }
ring = "0.16.9"
hex = "0.4.0"
strum_macros = "0.17.1"

[dev-dependencies]
toml = "0.5.5"
lazy_static = "1.4.0"
