[package]
name = "cex_trading_example"
version = "0.1.2"
authors = ["Sergey Isaev <isvforall@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cexio = "0.5.3"